# Generated by Django 3.2.9 on 2021-12-04 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countmodel',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='количество', to='recipes.ingredientmodel'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='рецепты', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=models.ManyToManyField(related_name='рецепт', to='recipes.CountModel', verbose_name='ingredients'),
        ),
    ]
