# Generated by Django 3.2.9 on 2021-12-07 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211204_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countmodel',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='recipes.ingredientmodel'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', to='recipes.CountModel', verbose_name='ingredients'),
        ),
    ]
