# Generated by Django 3.2.9 on 2021-12-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_shoppingcartmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartmodel',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
