# Generated by Django 3.2.9 on 2021-12-22 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_rename_recipes_shoppingcartmodel_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='CountModel',
            new_name='Count',
        ),
        migrations.RenameModel(
            old_name='FavoriteModel',
            new_name='Favorite',
        ),
        migrations.RenameModel(
            old_name='IngredientModel',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='TagModel',
            new_name='Tag',
        ),
        migrations.RenameModel(
            old_name='RecipeModel',
            new_name='Recipe',
        ),
        migrations.DeleteModel(
            name='ShoppingCartModel',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='recipes.recipe', verbose_name='recipe'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
