# Generated by Django 3.2 on 2022-01-09 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_subcribemodel_subcribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcribe',
            name='subscribed',
            field=models.ForeignKey(help_text='Подписан', on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='subscribed'),
        ),
        migrations.AlterField(
            model_name='subcribe',
            name='subscriber',
            field=models.ForeignKey(help_text='Подписчик', on_delete=django.db.models.deletion.CASCADE, related_name='subscribed', to=settings.AUTH_USER_MODEL, verbose_name='subscriber'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Адрес электронной почты', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
